server:
  port: 8083
spring:
  kafka:
    # 以逗号分隔的地址列表，用于建立与Kafka集群的初始连接(kafka 默认的端口号为9092)
    bootstrap-servers: 10.10.10.99:9092
    producer:
      # 发生错误后，消息重发的次数。
      retries: 5
      #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
      batch-size: 16384000
      # 设置生产者内存缓冲区的大小。
      buffer-memory: 335544320
      # 键的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 值的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # acks=0 ： 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks=1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=all ：只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      acks: all
      compression-type: gzip
      client-id: 1
      properties:
        metadata:
          max:
            age:
              ms: 3000000
        send:
          buffer:
            bytes: 1310720
        receive:
          buffer:
            bytes: 32768
        max:
          request:
            size: 1048576
        reconnect:
          backoff:
            ms: 50
        transaction:
          timeout:
            ms: 60000
  #spring-security登录密码
  security:
    user:
      name: admin
      password: 123456
management:
  endpoints:
    web:
      exposure:
        include: "*"

